### ISSUE TITLE
Must scroll all the way back up to close popup message

### ISSUE THREAD

**Issue by jidanni** [osmus/dogwood#10]
(I'm not sure if this is the right place to report this.)

Here if a long item is encountered, when finished reading, the user must scroll all the way back up to the top, to be able to find the X popup closer button.

![20240418T102623](https://github.com/osmus/dogwood/assets/1230959/cb96f50b-c23d-46f8-bf27-0d768e71d2b4)

**Comment by quincylvania** [comment]
This has to do with the sessionize schedule module and is not part of OSMUS tech.
