### ISSUE TITLE
Add an additional set of day switcher buttons at the bottom of conference schedule template

### ISSUE THREAD

**Issue by jidanni** [osmus/dogwood#11]
Here we are at the top of the Friday schedule.
We will read to the very bottom, whereupon we intend to read the Saturday schedule.

![20240418T103443](https://github.com/osmus/dogwood/assets/1230959/89194265-1312-4438-b658-5c786b14e544)

Problem is: when we get to the bottom of Friday, we need to scroll all the way back up to find the button to switch to Saturday.

So do consider adding an additional set of day switcher buttons at the bottom too.

**Comment by quincylvania** [comment]
This has to do with the sessionize schedule module and is not part of OSMUS tech.
